
#ifndef SHAREMIND_MOD_ALGORITHMS_SINE_H
#define SHAREMIND_MOD_ALGORITHMS_SINE_H

#include "DeclareSyscall.h"


SHAREMIND_MOD_ALGORITHMS_DECLARE_SYSCALL(float32_sin)
SHAREMIND_MOD_ALGORITHMS_DECLARE_SYSCALL(float64_sin)

#endif /* SHAREMIND_MOD_ALGORITHMS_SINE_H */
